INSERT INTO USUARIO(nome, email, senha) VALUES('Andre', 'andre@gmail.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Bruno', 'bruno@yahoo.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Carlos', 'carlos@yahoo.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Daniel', 'daniel@gmail.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Erik', 'erik@gmail.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Fabiana', 'fabiana@outlook.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Gabriel', 'gabriel@yahoo.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Humberto', 'humberto@yahoo.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Igor', 'igor@gmail.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Jaqueline', 'jaqueline@outlook.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Kelly', 'kelly@gmail.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Leonardo', 'leonardo@gmail.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Monica', 'monica@yahoo.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Natalia', 'natalia@yahoo.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Otavio', 'otavio@outlook.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Paula', 'paula@gmail.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Queiroz', 'queiroz@aol.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Rebeca', 'rebeca@yahoo.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Sara', 'sara@yahoo.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Thais', 'thais@gmail.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Ulysess', 'ulysess@gmail.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Vitoria', 'vitoria@gmail.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('William', 'william@yahoo.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Xena', 'xena@mail.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Yan', 'yan@yahoo.com', '123456');
INSERT INTO USUARIO(nome, email, senha) VALUES('Zelia', 'zelia@yahoo.com', '123456');

INSERT INTO CURSO(nome, categoria) VALUES('Spring Boot', 'Programação');
INSERT INTO CURSO(nome, categoria) VALUES('HTML 5', 'Front-end');
INSERT INTO CURSO(nome, categoria) VALUES('CSS', 'Front-end');
INSERT INTO CURSO(nome, categoria) VALUES('JS', 'Front-end');
INSERT INTO CURSO(nome, categoria) VALUES('Angular', 'Front-end');

INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('Dúvida', 'Erro ao criar projeto', '2019-05-05 18:00:00', 'NAO_RESPONDIDO', 1, 1);
INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('Socorro', 'Projeto não compila', '2019-05-05 19:00:00', 'NAO_RESPONDIDO', 1, 5);
INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('O que eu faço', 'Tag HTML', '2019-05-05 20:00:00', 'NAO_RESPONDIDO', 1, 2);
INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('Mais perdido que o John Travolta', 'Erro de compilação', '2020-01-03 15:30:00', 'NAO_RESPONDIDO', 3, 2);
INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('Eu não sei', 'Função não faz o que eu esperava', '2021-06-10 20:45:00', 'NAO_RESPONDIDO', 4, 1);
INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('Erro while', 'Preciso de ajuda', '2022-01-20 08:30:00', 'NAO_RESPONDIDO', 4, 1);
INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('Erro Chrome', 'Preciso de ajuda', '2022-01-20 08:30:00', 'NAO_RESPONDIDO', 5, 1);
INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('Duvida ManyToOne', 'Preciso de ajuda', '2022-01-20 08:30:00', 'NAO_RESPONDIDO', 6, 1);
INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('Duvida JPA', 'Preciso de ajuda', '2022-01-20 08:30:00', 'NAO_RESPONDIDO', 6, 1);
INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('RestController', 'Preciso de ajuda', '2022-01-20 08:30:00', 'NAO_RESPONDIDO',7, 1);
INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('DeleteMapping', 'Preciso de ajuda', '2022-01-20 08:31:00', 'NAO_RESPONDIDO', 8, 1);
INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('Transactional', 'Preciso de ajuda', '2022-01-20 08:32:00', 'NAO_RESPONDIDO', 9, 1);
INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('RequestMapping', 'Preciso de ajuda', '2022-01-20 08:40:00', 'NAO_RESPONDIDO', 10, 1);
INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('Autowired', 'Preciso de ajuda', '2022-01-20 08:45:00', 'NAO_RESPONDIDO', 7, 1);
INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('RequestMapping', 'Preciso de ajuda', '2022-01-20 09:30:00', 'NAO_RESPONDIDO', 4, 1);
INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('Override', 'Preciso de ajuda', '2022-01-20 10:00:00', 'NAO_RESPONDIDO', 8, 1);
INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('hashCode', 'Preciso de ajuda', '2022-01-20 10:01:00', 'NAO_RESPONDIDO', 20, 1);
INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('enum StatusTopico', 'Preciso de ajuda', '2022-01-20 10:30:00', 'NAO_RESPONDIDO', 24, 1);
INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('LocalDateTime', 'Preciso de ajuda', '2022-01-20 11:30:00', 'NAO_RESPONDIDO', 10, 1);